data/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "data"

urlpatterns = [
    path("", views.data, name="data"),
    path("get_scrap_data/", views.get_scrap_data, name="get_scrap_data"),
    path("get_data/", views.get_data, name="get_data"),
    path("accepted_data/", views.accepted_data, name='accepted_data'),
    path("accepted_modification/", views.accepted_modification, name='accepted_modification'),
    path("rejected_data/", views.rejected_data, name='reject_data'),
    path("accepted/", views.accepted, name='accepted'),
    path("rejected/", views.rejected, name='rejected'),
    path('upload/', views.upload_csv, name='upload_csv'),
    path('success/', views.success_page, name='success_page'),
    path('feedback_data/<int:data_id>/', views.feedback_data, name='feedback_data'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legislative/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "legislative"

urlpatterns = [
    # path("", views., name="legislative"),
    path("success/", views.success_page, name="success_page"),
    path("data_json/", views.data_json, name="data_json"),
    path("data/", views.data, name="data"),
    path('upload_member_csv/', views.upload_member_csv, name='upload_member_csv'),
    path('upload_committee_csv/', views.upload_committee_csv, name='upload_committee_csv'),
    path('upload_subcommittee_csv/', views.upload_subcommittee_csv, name='upload_subcommittee_csv'),
    path('upload_title_csv/', views.upload_title_csv, name='upload_title_csv'),
    path('upload_hierarchy_csv/', views.upload_hierarchy_csv, name='upload_hierarchy_csv'),
    path('upload_data/', views.upload_data, name='upload_data'),
]

web_scraping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("data.urls"), name="products"),
    path("legislative/", include("legislative.urls"), name="legislative"),

]

web_scraping/templates/base.html
{% load static %}

<style>

</style>

<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Font Style -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">

<scripts src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
  <!-- Search Highlight -->
  <script src="https://cdn.datatables.net/plug-ins/1.13.7/features/searchHighlight/dataTables.searchHighlight.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/plug-ins/1.13.7/features/searchHighlight/dataTables.searchHighlight.css">
  
  <link rel="stylesheet" href="{% static 'DataTables/datatables.min.css' %}">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
  


  <title>{% block title %}GovFinder{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand title-web" href="#">GovFinder</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'data' %}active{% endif %}" aria-current="page" href="{% url 'legislative:data' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'upload_data' %}active{% endif %}" href="{% url 'legislative:upload_data' %}">Upload Data</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'upload_member_csv' %}active{% endif %}" href="{% url 'legislative:upload_member_csv' %}">Upload CSV</a>
                  </li>
                  <!-- <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'rejected' %}active{% endif %}" href="{% url 'data:rejected' %}">Rejected</a>
                  </li> -->
                  <!-- <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'accepted_modification' %}active{% endif %}" href="{% url 'data:accepted_modification' %}">Modification</a>
                  </li> -->
                  <!-- <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'upload_csv' %}active{% endif %}" href="{% url 'data:upload_csv' %}">Upload CSV</a>
                  </li> -->
            </ul>

            <!-- <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
          </div>
        </div>
      </nav>
      <div id="loader" class="loader">

          <div class="spinner center">
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
              <div class="spinner-blade"></div>
            </div>
            
        </div>
    <div id="content">
        {% block body %}{% endblock body %}
    </div>
    <!-- Search Highlight JQ -->
    <script src="https://bartaz.github.io/sandbox.js/jquery.highlight.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static  'DataTables/datatables.min.js' %}"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
</body>
</html>