data/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "data"

urlpatterns = [
    path("", views.data, name="data"),
    path("get_scrap_data/", views.get_scrap_data, name="get_scrap_data"),
    path("get_data/", views.get_data, name="get_data"),
    path("accepted_data/", views.accepted_data, name='accepted_data'),
    path("accepted_modification/", views.accepted_modification, name='accepted_modification'),
    path("rejected_data/", views.rejected_data, name='reject_data'),
    path("accepted/", views.accepted, name='accepted'),
    path("rejected/", views.rejected, name='rejected'),
    path('upload/', views.upload_csv, name='upload_csv'),
    path('success/', views.success_page, name='success_page'),
    path('feedback_data/<int:data_id>/', views.feedback_data, name='feedback_data'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legislative/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "legislative"

urlpatterns = [
    # path("", views., name="legislative"),
    path("success/", views.success_page, name="success_page"),
    path("data_json/", views.data_json, name="data_json"),
    path("data/", views.data, name="data"),
    path('upload_member_csv/', views.upload_member_csv, name='upload_member_csv'),
    path('upload_committee_csv/', views.upload_committee_csv, name='upload_committee_csv'),
    path('upload_subcommittee_csv/', views.upload_subcommittee_csv, name='upload_subcommittee_csv'),
    path('upload_title_csv/', views.upload_title_csv, name='upload_title_csv'),
    path('upload_hierarchy_csv/', views.upload_hierarchy_csv, name='upload_hierarchy_csv'),
    path('upload_data/', views.upload_data, name='upload_data'),
]

web_scraping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("data.urls"), name="products"),
    path("legislative/", include("legislative.urls"), name="legislative"),

]

data/models.py
from django.db import models


class DataScrap(models.Model):
    name = models.CharField(max_length=512, null=True)
    dep = models.CharField(max_length=512, blank=True, null=True)
    designation = models.CharField(max_length=512, blank=True, null=True)
    address = models.CharField(max_length=512, blank=True, null=True)
    email = models.EmailField(max_length=512, blank=True, null=True)
    phone_number = models.CharField(max_length=512, blank=True, null=True)
    link = models.CharField(max_length=512, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    hierarchy = models.CharField(max_length=512, blank=True, null=True)
    image_name = models.TextField(blank=True, null=True)
    validation = models.BooleanField(default=False, null=True)

class Feedback(models.Model):
    data_scrap = models.ForeignKey(DataScrap, on_delete=models.CASCADE)
    feedback_data = models.TextField(blank=True, null=True)
    
class CSVFiles(models.Model):
    file_name = models.CharField(max_length=255, null=True)

data/forms.py
# forms.py
from django import forms
from .models import DataScrap, Feedback

class CSVUploadForm(forms.ModelForm):
    class Meta:
        model = DataScrap
        fields = []  # Empty fields to only allow file upload

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedback_data', ]

legislative/forms.py
from django import forms
from .models import *



class CSVMemberForm(forms.ModelForm):
    class Meta:
        model = Members
        fields = []


class CSVCommitteeForm(forms.ModelForm):
    class Meta:
        model = Committees
        fields = []

class CSVSubCommitteeForm(forms.ModelForm):
    class Meta:
        model = Committees
        fields = []


class CSVTitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = []


class CSVHierarchyForm(forms.ModelForm):
    class Meta:
        model = Hierarchy
        fields = []

class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = ['member', 'committee', 'subcommittee', 'title', 'hierarchy']
        widgets = {
            'member': forms.Select(attrs={'class': 'dropdown-field'}),
            'committee': forms.Select(attrs={'class': 'dropdown-field'}),
            'subcommittee': forms.Select(attrs={'class': 'dropdown-field'}),
            'title': forms.Select(attrs={'class': 'dropdown-field'}),
            'hierarchy': forms.Select(attrs={'class': 'dropdown-field'}),
        }

    # Optionally, you can customize the __init__ method to further modify form behavior
    # def __init__(self, *args, **kwargs):
    #     super(DataForm, self).__init__(*args, **kwargs)
    #     # Additional customizations here
        








# class DataForm(forms.ModelForm):
#     committee = forms.ModelMultipleChoiceField(
#         queryset=Committees.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False
#     )
#     subcommittee = forms.ModelMultipleChoiceField(
#         queryset=SubCommittees.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False
#     )
#     hierarchy = forms.ModelMultipleChoiceField(
#         queryset=Hierarchy.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False
#     )
#     title = forms.ModelMultipleChoiceField(
#         queryset=Title.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False
#     )

#     class Meta:
#         model = Data
#         fields = ['member', 'committee', 'subcommittee', 'title', 'hierarchy']

#     # Optionally, you can customize the __init__ method to further modify form behavior
#     # def __init__(self, *args, **kwargs):
#     #     super(DataForm, self).__init__(*args, **kwargs)
#     #     # Additional customizations here

data/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from .models import DataScrap, CSVFiles, Feedback
from django.core import serializers
from django.forms.models import model_to_dict
from django.views import View
from .forms import CSVUploadForm, FeedbackForm
import csv
import os
import zipfile
import tempfile

def data(request):
    return render(request, 'data/data.html')


def get_scrap_data(request):
    scrap_data = DataScrap.objects.all()
    data = [model_to_dict(s_data) for s_data in scrap_data]
    data = [{
        'id':s_data.id,
        'name': s_data.name,
        'designation': s_data.designation,
        'dep': s_data.dep,
        'address': s_data.address,
        'email': s_data.email,
        'phone_number': s_data.phone_number,
        'link':s_data.link,
        'desc':s_data.desc,
        'hierarchy': s_data.hierarchy,
        'image_name': s_data.image_name,
        'validation': None
    } for s_data in scrap_data]
    return JsonResponse({'scrap_data': data})

from django.core.paginator import Paginator, EmptyPage
import logging
from django.db.models import Q

logger = logging.getLogger(__name__)

def get_data(request, validation_status=None):
    try:
        if request.method == 'POST':
            # Handle POST request parameters
            validation_status = request.GET.get('validation_status')
            # modification = request.GET.get('modification')
            draw = int(request.POST.get('draw', 1))
            start = int(request.POST.get('start', 0))
            length = int(request.POST.get('length', 10000))

            # Assuming you want to order by 'id', adjust this based on your requirements
            order_column_index = int(request.POST.get('order[0][column]', 0))
            order_direction = request.POST.get('order[0][dir]', '')
            order_column_name = request.POST.get(f'columns[{order_column_index}][data]', 'id')
            ordering = f"{'' if order_direction == 'asc' else '-'}{order_column_name}"

            # Get the search value from the DataTables request
            search_value = request.POST.get('search[value]', '')

            # Get the hierarchy value from the DataTables request
            hierarchy_value = request.POST.get('columns[10][search][value]', '')

            # Use hierarchy_value as the search_value if it is not empty
            final_search_value = hierarchy_value if hierarchy_value else search_value

            # Define the filter conditions based on the columns you want to search
            filter_conditions = Q(id__iexact=final_search_value) | Q(name__icontains=final_search_value) | Q(designation__icontains=final_search_value) | Q(dep__icontains=final_search_value) | Q(hierarchy__icontains=final_search_value)
            
            print('Search value:', search_value)
            print('Hierarchy value:', hierarchy_value)
            if validation_status == 'null':
                scrap_data = DataScrap.objects.filter(validation__isnull=True).filter(filter_conditions).order_by(ordering)
            elif validation_status == 'true':
                scrap_data = DataScrap.objects.filter(validation=True).filter(filter_conditions).order_by(ordering)
            elif validation_status == 'false':
                scrap_data = DataScrap.objects.filter(validation=False).filter(filter_conditions).order_by(ordering)

            # elif validation_status == 'true' and modification == 'true':
            #     # scrap_data = DataScrap.objects.filter(validation=True).filter(filter_conditions).filter(feedback__feedback_data__isnull=False, feedback__feedback_data = '').order_by(ordering)
            #     scrap_data = DataScrap.objects.filter(
            #         filter_conditions,
            #         validation=True,
            #         ).exclude(
            #         Q(feedback__feedback_data__isnull=True) | Q(feedback__feedback_data='')
            #         ).order_by(ordering)
            else:
                # Default case: all data
                print("default")
                scrap_data = DataScrap.objects.filter(filter_conditions).order_by(ordering)

            paginator = Paginator(scrap_data, length)
            page = (start // length) + 1

            try:
                paginated_data = paginator.page(page)
            except EmptyPage:
                paginated_data = []

            data = []

            for s_data in paginated_data:
                feedback = Feedback.objects.filter(data_scrap=s_data).first()
                feedback_data = feedback.feedback_data if feedback else ""

                data_entry = {
                    'id': s_data.id,
                    'name': s_data.name,
                    'designation': s_data.designation,
                    'dep': s_data.dep,
                    'address': s_data.address,
                    'email': s_data.email,
                    'phone_number': s_data.phone_number,
                    'link': s_data.link,
                    'desc': s_data.desc,
                    'hierarchy': s_data.hierarchy,
                    'image_name': s_data.image_name,
                    'validation': s_data.validation,
                    'feedback_data': feedback_data,
                }

                data.append(data_entry)

            response = {
                'draw': draw,
                'recordsTotal': scrap_data.count(),
                'recordsFiltered': scrap_data.count(),
                'data': data,
            }

            return JsonResponse(response)
    except Exception as e:
        logging.error(f"Error in get_data view: {e}")
        return JsonResponse({'error': 'An error occurred while processing the request.'}, status=500)


def accepted_data(request):
    if request.method == "GET":
        id = request.GET.get("id")
        try:
            data = DataScrap.objects.get(pk=id)
            data.validation = True
            print(f"Data with ID {id} marked as validated.")
            data.save()
            # Convert the Leadership model instance to a dictionary
            data_dict = model_to_dict(data)
            return JsonResponse({"status": "success", 'data':data_dict})
        except DataScrap.DoesNotExist:
            return JsonResponse(
                {"status": "error", "message": "Data record not found."}, status=404
            )

    return JsonResponse(
        {"status": "error", "message": "Invalid request method."}, status=400
    )

def accepted(request):
    return render(request, 'data/accepted.html')

def accepted_modification(request):
    return render(request, 'data/modification.html')

def rejected_data(request):
    if request.method == "GET":
        id = request.GET.get("id")
        try:
            data = DataScrap.objects.get(pk=id)
            data.validation = False
            print(f"Data with ID {id} marked as validated.")
            data.save()
            # Convert the Leadership model instance to a dictionary
            data_dict = model_to_dict(data)
            return JsonResponse({"status": "success", 'data':data_dict})
        except DataScrap.DoesNotExist:
            return JsonResponse(
                {"status": "error", "message": "Data record not found."}, status=404
            )

    return JsonResponse(
        {"status": "error", "message": "Invalid request method."}, status=400
    )

def rejected(request):
    return render(request, 'data/rejected.html')


def upload_csv(request):
    if request.method == 'POST':
        csv_form = CSVUploadForm(request.POST, request.FILES)
        if csv_form.is_valid():
            csv_file = request.FILES['file']
            csv_file_name = csv_file.name

            decoded_file = csv_file.read().decode('utf-8')
            csv_data = csv.reader(decoded_file.splitlines(), delimiter=',')

            # Skip the header row
            next(csv_data)

            for row in csv_data:
                # Check if a record with the same values already exists
                existing_record = DataScrap.objects.filter(
                    name=row[0],
                    designation=row[1],
                    dep=row[2],
                ).first()

                if existing_record:
                    # Update the existing record with new data
                    existing_record.address = row[3]
                    existing_record.email = row[4]
                    existing_record.phone_number = row[5]
                    existing_record.link = row[6]
                    existing_record.desc = row[7]
                    existing_record.hierarchy = row[8]
                    existing_record.image_name = row[9]
                    existing_record.validation = existing_record.validation
                    existing_record.save()
                else:
                    # Create a new instance of DataScrap with appropriate field values
                    DataScrap.objects.create(              
                        name=row[0],
                        designation=row[1],
                        dep=row[2],
                        address=row[3],
                        email=row[4],
                        phone_number=row[5],
                        link=row[6],
                        desc=row[7],
                        hierarchy=row[8],
                        image_name=row[9],
                        validation=None
                    )

            # Save the file name in the CSVFiles model
            csv_files_data = CSVFiles(file_name=csv_file_name)
            csv_files_data.save()

            return redirect('data:success_page')
    else:
        csv_form = CSVUploadForm()

    db_csv_files = CSVFiles.objects.all()

    return render(request, 'data/upload.html', {'form': csv_form, 'csv_files': db_csv_files})



def success_page(request):
    return render(request, 'data/success.html')

def feedback_data(request, data_id):

legislative/templates/create_committee.html
<form method="post" action="{% url 'legislative:committee' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

legislative/templates/create_data.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Data</title>
    {{ form.media.css }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ form.media.js }}
</head>

<body>
    <h1>Create Data</h1>
    
    <form method="post" action="{% url 'legislative:dataform' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</body>

</html>

legislative/templates/create_member.html
<form method="post" action="{% url 'legislative:member' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

legislative/templates/create_subcommittee.html
<form method="post" action="{% url 'legislative:subcommittee' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

legislative/templates/data.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Data</title>
</head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<body>



    <table id="legislative-table" class="legislative_data center table table-striped table-bordered">


    </table>

</body>
</html>


{% endblock body %}

legislative/templates/success_page.html
<h1>Success</h1>

legislative/templates/upload.html
{% extends "base.html" %}

{% block body %}

<style>
    .filterDiv{
        display: none;
    }
    .loader{
        display: none !important;
    }
</style>
<!DOCTYPE html>
<html>
<head>
    <title>Upload CSV</title>
</head>
<body>

    <div>
        <a class="nav-link {% if request.resolver_match.url_name == 'upload_member_csv' %}active{% endif %}" href="{% url 'legislative:upload_member_csv' %}">Member CSV</a>
        <a class="nav-link {% if request.resolver_match.url_name == 'upload_committee_csv' %}active{% endif %}" href="{% url 'legislative:upload_committee_csv' %}">Committee CSV</a>
        <a class="nav-link {% if request.resolver_match.url_name == 'upload_subcommittee_csv' %}active{% endif %}" href="{% url 'legislative:upload_subcommittee_csv' %}">SubCommittee CSV</a>
        <a class="nav-link {% if request.resolver_match.url_name == 'upload_title_csv' %}active{% endif %}" href="{% url 'legislative:upload_title_csv' %}">Title CSV</a>
        <a class="nav-link {% if request.resolver_match.url_name == 'upload_hierarchy_csv' %}active{% endif %}" href="{% url 'legislative:upload_hierarchy_csv' %}">Hierarchy CSV</a>
    </div>

    <div class="upload_div">
        <div>
            <h1>Upload a CSV File</h1>
            <form method="post" enctype="multipart/form-data" id="csv-form">
                {% csrf_token %}
                {{ member_form.as_p }}
                {{ committee_form.as_p }}
                {{ subcommittee_form.as_p }}
                {{ title_form.as_p }}
                <input class="btn btn-secondary" type="file" name="file">
                <button class="btn btn-primary" type="submit" id="upload-button">Upload</button>
            </form>
        </div>
    </div>


</body>
<!-- <script>
    $(document).ready(function () {
        // Function to check if the form is filled
        function isFormFilled() {
            // You can add more conditions to check other form fields if needed
            return $.trim($("input[name='file']").val()) !== '';
        }

        // Enable the button when the form is filled
        $("#csv-form").on("input", function () {
            if (isFormFilled()) {
                $("#upload-button").prop("disabled", false);
            } else {
                $("#upload-button").prop("disabled", true);
            }
        });
    });
</script> -->
</html>

{% endblock body %}

legislative/templates/upload_data.html
{% extends "base.html" %}

{% block body %}

<style>
    .dropdown-field {
        display: block;
        margin-bottom: 10px;  /* Adjust as needed */
    }
</style>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>



{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
  </ul>
  <script>
    // Add a script to automatically close the alert after 2 seconds
    setTimeout(function() {
      document.querySelector('.messages').style.display = 'none';
    }, 1500);
  </script>
{% endif %}

{% endblock body %}